/*-- Tabla Users
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE
    --CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Montana
CREATE TABLE Montana (
    MontanaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Altura NUMBER(7,2) NOT NULL,
    Ubicacion VARCHAR2(100) NOT NULL,
    Descripcion VARCHAR2(255) NOT NULL
    --Imagen VARCHAR2(255) NOT NULL
);

-- Tabla Ruta
CREATE TABLE Ruta (
    RutaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MontanaID NUMBER NOT NULL,
    Dificultad VARCHAR2(20) CHECK (Dificultad IN ('Facil', 'Intermedia', 'Dificil')) NOT NULL,
    Descripcion VARCHAR2(255) NOT NULL,
    --Duracion INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    Distancia NUMBER(7,2) NOT NULL,
    FOREIGN KEY (MontanaID) REFERENCES Montana(MontanaID) ON DELETE CASCADE
);*/


-- Inserciones en Montana (no ponemos MontanaID porque es IDENTITY)
INSERT INTO Montana (Nombre, Altura, Ubicacion, Descripcion) VALUES ('Pico Everest', 8848.86, 'Nepal/Tíbet', 'La montaña más alta del mundo');
INSERT INTO Montana (Nombre, Altura, Ubicacion, Descripcion) VALUES ('Monte Kilimanjaro', 5895.00, 'Tanzania', 'El pico más alto de África');
INSERT INTO Montana (Nombre, Altura, Ubicacion, Descripcion) VALUES ('Monte Fuji', 3776.24, 'Japón', 'Volcán activo y símbolo nacional de Japón');

-- Para saber qué MontanaID tienen los registros recién insertados, ejecuta:
-- SELECT MontanaID, Nombre FROM Montana;

-- Supongamos que MontanaID asignados fueron 1, 2, y 3 respectivamente.

-- Inserciones en Ruta usando los MontanaID
INSERT INTO Ruta (MontanaID, Dificultad, Descripcion, Distancia) VALUES (1, 'Dificil', 'Ruta de ascenso técnico al Everest', 20.50);
INSERT INTO Ruta (MontanaID, Dificultad, Descripcion, Distancia) VALUES (2, 'Intermedia', 'Ruta para escalar el Kilimanjaro', 15.00);
INSERT INTO Ruta (MontanaID, Dificultad, Descripcion, Distancia) VALUES (3, 'Facil', 'Caminata sencilla alrededor del Monte Fuji', 8.30);
INSERT INTO Ruta (MontanaID, Dificultad, Descripcion, Distancia) VALUES (1, 'Intermedia', 'Ruta alternativa para el Everest', 18.75);
INSERT INTO Ruta (MontanaID, Dificultad, Descripcion, Distancia) VALUES (2, 'Dificil', 'Ruta técnica para Kilimanjaro desde el oeste', 17.20);

