-- Tabla Users
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE
    --CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Montaña
CREATE TABLE Montaña (
    MontañaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Altura NUMBER(7,2) NOT NULL,
    Ubicacion VARCHAR2(100) NOT NULL,
    Descripcion VARCHAR2(255) NOT NULL,
    --Imagen VARCHAR2(255) NOT NULL
);

-- Tabla Ruta
CREATE TABLE Ruta (
    RutaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MontañaID NUMBER NOT NULL,
    Dificultad VARCHAR2(20) CHECK (Dificultad IN ('Fácil', 'Intermedia', 'Difícil')) NOT NULL,
    Descripcion VARCHAR2(255) NOT NULL,
    --Duracion INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    Distancia NUMBER(7,2) NOT NULL,
    FOREIGN KEY (MontañaID) REFERENCES Montaña(MontañaID) ON DELETE CASCADE
);

/*-- Tabla Material
CREATE TABLE Material (
    MaterialID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Descripcion CLOB NOT NULL,
    Cantidad NUMBER NOT NULL CHECK (Cantidad >= 0)
);

-- Tabla RutaMaterial
CREATE TABLE RutaMaterial (
    RutaID NUMBER,
    MaterialID NUMBER,
    PRIMARY KEY (RutaID, MaterialID),
    FOREIGN KEY (RutaID) REFERENCES Ruta(RutaID) ON DELETE CASCADE,
    FOREIGN KEY (MaterialID) REFERENCES Material(MaterialID) ON DELETE CASCADE
);*/

